call plug#begin('~/.config/nvim/autoload/plugged')
	Plug 'nvim-tree/nvim-tree.lua'
	Plug 'nvim-telescope/telescope.nvim'
	Plug 'nvim-lua/plenary.nvim'
	Plug 'karb94/neoscroll.nvim'
	Plug 'nvim-tree/nvim-web-devicons'
	Plug 'nvim-lualine/lualine.nvim'
	Plug 'andweeb/presence.nvim'
call plug#end()
